rootProject.name = "java-otus-hw"
include("hw01-gradle")
include("hw02-generics")
include("hw03-annotations")
include("hw04-gc")
include("hw05-aop")
include("hw06-atm")
include("hw07-patterns")
include("hw08-serialization")
include("hw09-jdbc")
include("hw10-jpql")
include("hw11-cache")
include("hw12-webServer")
include("hw13-di")
include("hw14-springDataJdbc")
include("hw15-executors")
